

service: aws-simple-scraper

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  memorySize: 128
  versionFunctions: false
  iamRoleStatements:
      - Effect: Allow
        Action: 
            - ses:SendEmail
        Resource: "*"
  
functions:
  scheduled-cron:
    handler: handler.schedule_entry
    events:
        # Invoke
        - schedule: rate(3 hours)
  http-get:
    handler: handler.api_entry
    events:
        - http:
            path: ping
            method: get
            cors: true
    
plugins:
  - serverless-python-requirements
