# ************************************
# Authors: Mark Monteno (u3154816)
# Assignment 1 Term project: Serverless Computing
# Configuration file for Serverless
# ************************************

# Name of our service
service: aws-simple-scraper

# Provider information, etc.
provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  memorySize: 128
  versionFunctions: false
  iamRoleStatements:
      - Effect: Allow
        Action: 
            - ses:SendEmail
        Resource: "*"
  
# Function information, etc.  
functions:
  scheduled-cron:
    handler: handler.schedule_entry
    events:
        # Invoke
        - schedule: rate(24 hours)
  http-get:
    handler: handler.api_entry
    events:
        - http:
            path: ping
            method: get
            cors: true
    
# Plugin requirements, etc.    
plugins:
  - serverless-python-requirements
