

service: aws-simple-scraper

provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  memorySize: 128
  versionFunctions: false
  iamRoleStatements:
      - Effect: Allow
        Action: 
            - ses:SendEmail
        Resource: "*"
  
functions:
  scrape:
    handler: handler.entry
  scheduled-cron:
    handler: handler.schedule
    events:
        # Invoke
        - schedule: rate(3 hours)
    
plugins:
  - serverless-python-requirements
